apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfe-orchestrator
  labels:
    app: nfe-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfe-orchestrator
  template:
    metadata:
      labels:
        app: nfe-orchestrator
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
      - name: nfe-orchestrator
        image: ghcr.io/lucianouziti/nfe-orchestrator:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: nfe-orchestrator-config
        resources:
          requests:
            cpu: "100m"
            memory: "156Mi"
          limits:
            cpu: "600m"
            memory: "500Mi"